### ISSUE TITLE
v0.9.2: Splitter: Language check for Italian comes up as English

### ISSUE THREAD

**Issue by andrewferlitsch** [andrewferlitsch/Gap#49]
The test of the file tests/files/lang-it.txt is reported by the Document class as English instead of Italian.

**Comment by virtualdvid** [comment]
The issue is when it detects the same quantity of words by language. Given the similarity between languages with Latin roots as we can see here:

en 4
False
**es 7**
False
fr 3
False
**it 7**
False
de 0
False

I don't know why it is assigning `en` by default when verify is `False`.

If you change the value (12) in the iterator `for` like (13 or 15) on the function `_langcheck`. In this way `lang-it.txt` will pass the test.

I fixed the function to evaluate a list of values and if the list contains duplicates run a new iteration until the list have unique values.

**Comment by andrewferlitsch** [comment]
That makes sense :)

Andy

**Comment by andrewferlitsch** [comment]
Fixed in v0.9.3
